### ISSUE TITLE
Releasing 0.12.0 Stalled

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigtable#51]
0.12.0 was not released 16 days ago due to some error: https://circleci.com/gh/googleapis/nodejs-bigtable/1109

I'm trying to get the release through now, but we're stalled on a new error.

@kolodny could you please take a look?

https://circleci.com/gh/googleapis/nodejs-bigtable/1408:

```
1) Bigtable/Table
       mutate()
         valid mutation:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  2) Bigtable/Table
       mutate()
         retries the failed mutations:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  3) Bigtable/Table
       mutate()
         has a `PartialFailureError` error when an entry fails after the retries:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  4) Bigtable/Table
       mutate()
         does not retry unretryable mutations:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  5) Bigtable/Table
       mutate()
         considers network errors towards the retry count:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules/lolex/src/lolex-src.js:671:15)
      at Context.done (system-test/mutate-rows.js:132:15)

  6) Bigtable/Table
       createReadStream
         simple read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  7) Bigtable/Table
       createReadStream
         retries a failed read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  8) Bigtable/Table
       createReadStream
         resets the retry counter after a successful read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  9) Bigtable/Table
       createReadStream
         moves the start point of a range being consumed:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  10) Bigtable/Table
       createReadStream
         removes ranges already consumed:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  11) Bigtable/Table
       createReadStream
         removes keys already read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  12) Bigtable/Table
       createReadStream
         adjust the limit based on the number of rows read:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)

  13) Bigtable/Table
       createReadStream
         does the previous 5 things in one giant test case:

      AssertionError [ERR_ASSERTION]: .on('end') shoud have been invoked
      + expected - actual

      -false
      +true
      
      at Context.it (system-test/read-rows.js:138:11)
```

**Comment by kolodny** [comment]
Very weird, I can't replicate. Try re-releasing? It may have been a transient bug

**Comment by stephenplusplus** [comment]
@kolodny do we need the same patch you figured out for the GAPIC PR?

**Comment by stephenplusplus** [comment]
@kolodny @sduskis we're still stuck with failures from the `system-test/mutate-rows.js` test suite. Could you please take a look?

```
  Bigtable/Table
    mutate()
      1) valid mutation
      2) retries the failed mutations
      3) has a `PartialFailureError` error when an entry fails after the retries
      4) does not retry unretryable mutations
      5) considers network errors towards the retry count


  0 passing (200ms)
  5 failing

  1) Bigtable/Table
       mutate()
         valid mutation:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules\lolex\src\lolex-src.js:671:15)
      at Context.done (system-test\mutate-rows.js:128:15)

  2) Bigtable/Table
       mutate()
         retries the failed mutations:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules\lolex\src\lolex-src.js:671:15)
      at Context.done (system-test\mutate-rows.js:128:15)

  3) Bigtable/Table
       mutate()
         has a `PartialFailureError` error when an entry fails after the retries:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules\lolex\src\lolex-src.js:671:15)
      at Context.done (system-test\mutate-rows.js:128:15)

  4) Bigtable/Table
       mutate()
         does not retry unretryable mutations:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules\lolex\src\lolex-src.js:671:15)
      at Context.done (system-test\mutate-rows.js:128:15)

  5) Bigtable/Table
       mutate()
         considers network errors towards the retry count:
     Error: Aborting after running 1000 timers, assuming an infinite loop!
      at Object.runAll (node_modules\lolex\src\lolex-src.js:671:15)
      at Context.done (system-test\mutate-rows.js:128:15)
```

**Comment by kolodny** [comment]
I opened #59 with a fix. [The issue was not having a projectId on the bigtable instance](https://github.com/kolodny/nodejs-bigtable/commit/2772e9398f79649b6d7de94b649b34ed7b5edca1#diff-0cedc9221fec4b33142665cc44113ca1R50) nodejs-common has the [throwing code](https://github.com/googleapis/nodejs-common/blob/6f6178bd833219a76735d39d4e1d857871096a7f/src/util.js#L565-L567). I'm not sure what changed which caused the error to only show up now

**Comment by stephenplusplus** [comment]
Thanks! How did you track it down to that throwing code link? The error I got above doesn’t seem related at first glance.

**Comment by kolodny** [comment]
Sure!

It was a matter of putting a debugger in the mocha code where it tries to runAll and see that it keeps adding more items to the run loop, when I looked at where those items were being set I saw it was in the `try catch` or decorateRequest which I was able to see the error text of not having a `projectId`. I cleaned up the code a drop to make sure things like this don't happen in the future and to make the error failure in the test reflect the actual error if it doesn't match an error we're respecting (it threw on an assert too fast to get the useful error message)

By the way I could have put a debugger in the `onBatchResponse` callback too for the same result, would have probably been easier too, `hindsight === 20/20`

**Comment by stephenplusplus** [comment]
Gotcha, thank you for the explanation!
