### ISSUE TITLE
Clusters of the instance is no longer in use after deleting the instance.

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/nodejs-bigtable#659]
**This is an open Discussion:**

`instance.delete` is only delete the instance, clusters are remain as it is but, [document](https://cloud.google.com/bigtable/docs/deleting-instance)  say deleting instance will permanently delete the instance's clusters.

while creating instance with same cluster it throws error:
```ts
Error: 6 ALREADY_EXISTS: Cannot re-create cluster 'ssd-cluster-7' in a different instance
    at Object.callErrorFromStatus (F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
    at Http2CallStream.<anonymous> (F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
    at Http2CallStream.emit (events.js:333:22)
    at F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\call-stream.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 6,
  details: "Cannot re-create cluster 'ssd-cluster-7' in a different instance",
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

Currently there is no way to delete the cluster.

**Before Deleting the Instance**
Try to delete cluster before deleting the instance it gives `FAILED_PRECONDITION` exception as below:
```ts
Error: 9 FAILED_PRECONDITION: Cannot delete the last LIVE Cluster in an Instance: projects/project-id/instances/test-instance-1/clusters/ssd-cluster-9
    at Object.callErrorFromStatus (F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
    at Http2CallStream.<anonymous> (F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
    at Http2CallStream.emit (events.js:333:22)
    at F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\call-stream.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 9,
  details: 'Cannot delete the last LIVE Cluster in an Instance: projects/project-id/instances/test-instance-1/clusters/ssd-cluster-9',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**After Instance Delete**
In case try to delete the cluster after Deleting the instance it throws `NOT_FOUND` exception:
```ts
Error: 5 NOT_FOUND: Instance projects/project-id/instances/test-instance-1 not found.
    at Object.callErrorFromStatus (F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
    at Http2CallStream.<anonymous> (F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
    at Http2CallStream.emit (events.js:333:22)
    at F:\common-test\bigtable-demos\node_modules\@grpc\grpc-js\build\src\call-stream.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 5,
  details: 'Instance projects/project-id/instances/test-instance-1 not found.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

Cluster of the specific instance is no longer in use after deleting the instance and it can not be delete as well.

/cc:
@stephenplusplus
@AVaksman 
@bcoe

**Comment by AVaksman** [comment]
@laljikanjareeya thanks for reporting it.
I believe the root cause might be in the fact that deleting an instance is eventually consistent.
Especially when instances with up to 4 clusters in different replication state may be involved.

**Comment by crwilcox** [comment]
This seems to be a documentation improvement request. https://cloud.google.com/bigtable/docs/deleting-instance could make it clear that deletion of instance/cluster is eventually consistent. I am opening an issue to look into update cloud.google.com

Tracked at b/169080009.

**Comment by cshaff0524** [comment]
This is a known issue. When you delete a cluster, you are prevented from creating a new cluster with the same ID for about a week, unless you create the cluster in the same instance that previously contained it.

This issue can't be fixed until after the [API v1 shutdown](https://cloud.google.com/bigtable/docs/deprecations/v1-api-shutdown) is complete.
